/* ConfFile.c generated by valac 0.18.1, the Vala compiler
 * generated from ConfFile.vala, do not modify */

/*Copyright (C) 2013 Mattias Münster

Author: Mattias Münster <mattiasmun@gmail.com>

This file is part of valamathg.

valamathg is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

valamathg is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with valamathg.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define MATHG_TYPE_CONF_FILE (mathg_conf_file_get_type ())
typedef struct _mathgConfFile mathgConfFile;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _mathgConfFile {
};


extern GFile* mathg_conf_file__f;
GFile* mathg_conf_file__f = NULL;

GType mathg_conf_file_get_type (void) G_GNUC_CONST;
mathgConfFile* mathg_conf_file_dup (const mathgConfFile* self);
void mathg_conf_file_free (mathgConfFile* self);
GFile* mathg_conf_file_cfgfile (void);
void mathg_conf_file_chkdir (GFile* f);
gchar** mathg_conf_file_getdata (GFile* f, int* result_length1);
static gint _vala_array_length (gpointer array);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GFile* mathg_conf_file_cfgfile (void) {
	GFile* result = NULL;
	GFile* _tmp0_;
	GFile* _tmp8_;
	GFile* _tmp9_;
	_tmp0_ = mathg_conf_file__f;
	if (_tmp0_ == NULL) {
		const gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		gchar* s;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		const gchar* _tmp5_;
		GFile* _tmp6_ = NULL;
		GFile* _tmp7_;
		_tmp1_ = g_get_user_config_dir ();
		_tmp2_ = g_strdup (_tmp1_);
		s = _tmp2_;
		_tmp3_ = s;
		_tmp4_ = g_strconcat (_tmp3_, "/valamathg/valamathg.conf", NULL);
		_g_free0 (s);
		s = _tmp4_;
		_tmp5_ = s;
		_tmp6_ = g_file_new_for_path (_tmp5_);
		_g_object_unref0 (mathg_conf_file__f);
		mathg_conf_file__f = _tmp6_;
		_tmp7_ = mathg_conf_file__f;
		mathg_conf_file_chkdir (_tmp7_);
		_g_free0 (s);
	}
	_tmp8_ = mathg_conf_file__f;
	_tmp9_ = _g_object_ref0 (_tmp8_);
	result = _tmp9_;
	return result;
}


void mathg_conf_file_chkdir (GFile* f) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (f != NULL);
	{
		GFile* _tmp0_;
		GFile* _tmp1_ = NULL;
		GFile* _tmp2_;
		gboolean _tmp3_ = FALSE;
		gboolean _tmp4_;
		_tmp0_ = f;
		_tmp1_ = g_file_get_parent (_tmp0_);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_file_query_exists (_tmp2_, NULL);
		_tmp4_ = !_tmp3_;
		_g_object_unref0 (_tmp2_);
		if (_tmp4_) {
			GFile* _tmp5_;
			GFile* _tmp6_ = NULL;
			GFile* _tmp7_;
			_tmp5_ = f;
			_tmp6_ = g_file_get_parent (_tmp5_);
			_tmp7_ = _tmp6_;
			g_file_make_directory_with_parents (_tmp7_, NULL, &_inner_error_);
			_g_object_unref0 (_tmp7_);
			if (_inner_error_ != NULL) {
				goto __catch0_g_error;
			}
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp8_;
		GError* _tmp9_;
		const gchar* _tmp10_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp8_ = stderr;
		_tmp9_ = e;
		_tmp10_ = _tmp9_->message;
		fprintf (_tmp8_, "%s\n", _tmp10_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


gchar** mathg_conf_file_getdata (GFile* f, int* result_length1) {
	gchar** result = NULL;
	gchar* _tmp0_;
	gchar* s;
	const gchar* _tmp25_;
	gchar** _tmp26_;
	gchar** _tmp27_ = NULL;
	gchar** _tmp28_;
	gint _tmp28__length1;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (f != NULL, NULL);
	_tmp0_ = g_strdup ("");
	s = _tmp0_;
	{
		GFile* _tmp1_;
		gboolean _tmp2_ = FALSE;
		_tmp1_ = f;
		_tmp2_ = g_file_query_exists (_tmp1_, NULL);
		if (_tmp2_) {
			GFile* _tmp3_;
			GFileInputStream* _tmp4_ = NULL;
			GFileInputStream* _tmp5_;
			GFileInputStream* _tmp6_;
			GDataInputStream* _tmp7_;
			GDataInputStream* _tmp8_;
			GDataInputStream* data_stream;
			gsize st = 0UL;
			GDataInputStream* _tmp9_;
			gsize _tmp10_ = 0UL;
			gchar* _tmp11_ = NULL;
			gchar* _tmp12_;
			_tmp3_ = f;
			_tmp4_ = g_file_read (_tmp3_, NULL, &_inner_error_);
			_tmp5_ = _tmp4_;
			if (_inner_error_ != NULL) {
				goto __catch1_g_error;
			}
			_tmp6_ = _tmp5_;
			_tmp7_ = g_data_input_stream_new ((GInputStream*) _tmp6_);
			_tmp8_ = _tmp7_;
			_g_object_unref0 (_tmp6_);
			data_stream = _tmp8_;
			_tmp9_ = data_stream;
			_tmp11_ = g_data_input_stream_read_line_utf8 (_tmp9_, &_tmp10_, NULL, &_inner_error_);
			st = _tmp10_;
			_tmp12_ = _tmp11_;
			if (_inner_error_ != NULL) {
				_g_object_unref0 (data_stream);
				goto __catch1_g_error;
			}
			_g_free0 (s);
			s = _tmp12_;
			_g_object_unref0 (data_stream);
		} else {
			GFile* _tmp13_;
			GFileOutputStream* _tmp14_ = NULL;
			GFileOutputStream* _tmp15_;
			GFileOutputStream* _tmp16_;
			GDataOutputStream* _tmp17_;
			GDataOutputStream* _tmp18_;
			GDataOutputStream* data_stream;
			gchar* _tmp19_;
			GDataOutputStream* _tmp20_;
			const gchar* _tmp21_;
			_tmp13_ = f;
			_tmp14_ = g_file_create (_tmp13_, G_FILE_CREATE_NONE, NULL, &_inner_error_);
			_tmp15_ = _tmp14_;
			if (_inner_error_ != NULL) {
				goto __catch1_g_error;
			}
			_tmp16_ = _tmp15_;
			_tmp17_ = g_data_output_stream_new ((GOutputStream*) _tmp16_);
			_tmp18_ = _tmp17_;
			_g_object_unref0 (_tmp16_);
			data_stream = _tmp18_;
			_tmp19_ = g_strdup ("10 1 10 +/ 2 20 .01");
			_g_free0 (s);
			s = _tmp19_;
			_tmp20_ = data_stream;
			_tmp21_ = s;
			g_data_output_stream_put_string (_tmp20_, _tmp21_, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (data_stream);
				goto __catch1_g_error;
			}
			_g_object_unref0 (data_stream);
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		FILE* _tmp22_;
		GError* _tmp23_;
		const gchar* _tmp24_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp22_ = stderr;
		_tmp23_ = e;
		_tmp24_ = _tmp23_->message;
		fprintf (_tmp22_, "%s\n", _tmp24_);
		_g_error_free0 (e);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		_g_free0 (s);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp25_ = s;
	_tmp27_ = _tmp26_ = g_strsplit (_tmp25_, " ", 0);
	_tmp28_ = _tmp27_;
	_tmp28__length1 = _vala_array_length (_tmp26_);
	if (result_length1) {
		*result_length1 = _tmp28__length1;
	}
	result = _tmp28_;
	_g_free0 (s);
	return result;
}


mathgConfFile* mathg_conf_file_dup (const mathgConfFile* self) {
	mathgConfFile* dup;
	dup = g_new0 (mathgConfFile, 1);
	memcpy (dup, self, sizeof (mathgConfFile));
	return dup;
}


void mathg_conf_file_free (mathgConfFile* self) {
	g_free (self);
}


GType mathg_conf_file_get_type (void) {
	static volatile gsize mathg_conf_file_type_id__volatile = 0;
	if (g_once_init_enter (&mathg_conf_file_type_id__volatile)) {
		GType mathg_conf_file_type_id;
		mathg_conf_file_type_id = g_boxed_type_register_static ("mathgConfFile", (GBoxedCopyFunc) mathg_conf_file_dup, (GBoxedFreeFunc) mathg_conf_file_free);
		g_once_init_leave (&mathg_conf_file_type_id__volatile, mathg_conf_file_type_id);
	}
	return mathg_conf_file_type_id__volatile;
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



