/* Frams.c generated by valac 0.18.1, the Vala compiler
 * generated from Frams.vala, do not modify */

/*Copyright (C) 2013 Mattias Münster

Author: Mattias Münster <mattiasmun@gmail.com>

This file is part of valamathg.

valamathg is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

valamathg is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with valamathg.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include "valamathg.h"
#include <gtk/gtk.h>
#include <gdk/gdk.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))



void _vala_main (gchar** args, int args_length1);
void frame (GtkWindow* gw, gchar** args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


void _vala_main (gchar** args, int args_length1) {
	GFile* _tmp0_ = NULL;
	GFile* _tmp1_;
	gint _tmp2_ = 0;
	gchar** _tmp3_ = NULL;
	gchar** _tmp4_;
	gint _tmp4__length1;
	gchar** data;
	gint data_length1;
	gint _data_size_;
	GtkWindow* _tmp5_;
	GtkWindow* gw;
	gchar** _tmp6_;
	gint _tmp6__length1;
	_tmp0_ = mathg_conf_file_cfgfile ();
	_tmp1_ = _tmp0_;
	_tmp3_ = mathg_conf_file_getdata (_tmp1_, &_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp2_;
	_g_object_unref0 (_tmp1_);
	data = _tmp4_;
	data_length1 = _tmp4__length1;
	_data_size_ = data_length1;
	args = data;
	args_length1 = data_length1;
	gtk_init (&args_length1, &args);
	_tmp5_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	g_object_ref_sink (_tmp5_);
	gw = _tmp5_;
	_tmp6_ = args;
	_tmp6__length1 = args_length1;
	frame (gw, _tmp6_, _tmp6__length1);
	gtk_main ();
	_g_object_unref0 (gw);
	data = (_vala_array_free (data, data_length1, (GDestroyNotify) g_free), NULL);
}


int main (int argc, char ** argv) {
	g_type_init ();
	_vala_main (argv, argc);
	return 0;
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


void frame (GtkWindow* gw, gchar** args, int args_length1) {
	GtkWindow* _tmp0_;
	GtkWindow* _tmp1_;
	gint _tmp2_ = 0;
	GtkWindow* _tmp3_;
	gchar** _tmp4_;
	gint _tmp4__length1;
	mathgEventCog* _tmp5_;
	mathgEventCog* ec;
	GtkWindow* _tmp6_;
	GtkWindow* _tmp7_;
	g_return_if_fail (gw != NULL);
	_tmp0_ = gw;
	gtk_window_set_title (_tmp0_, "valamathg");
	_tmp1_ = gw;
	_tmp2_ = gdk_screen_width ();
	gtk_window_set_default_size (_tmp1_, _tmp2_, 206);
	_tmp3_ = gw;
	g_signal_connect ((GtkWidget*) _tmp3_, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	_tmp4_ = args;
	_tmp4__length1 = args_length1;
	_tmp5_ = mathg_event_cog_new (_tmp4_, _tmp4__length1);
	g_object_ref_sink (_tmp5_);
	ec = _tmp5_;
	_tmp6_ = gw;
	gtk_container_add ((GtkContainer*) _tmp6_, (GtkWidget*) ec);
	_tmp7_ = gw;
	gtk_widget_show_all ((GtkWidget*) _tmp7_);
	mathg_event_cog_repaint (ec);
	_g_object_unref0 (ec);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



