/* MathCog.c generated by valac 0.18.1, the Vala compiler
 * generated from MathCog.vala, do not modify */

/*Copyright (C) 2013 Mattias Münster

Author: Mattias Münster <mattiasmun@gmail.com>

This file is part of valamathg.

valamathg is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

valamathg is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with valamathg.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define MATHG_TYPE_MATH_COG (mathg_math_cog_get_type ())

#define MATHG_TYPE_NUMBER_UTILS (mathg_number_utils_get_type ())
typedef struct _mathgNumberUtils mathgNumberUtils;

#define MATHG_TYPE_OPERATE (mathg_operate_get_type ())
typedef struct _mathgOperate mathgOperate;

#define MATHG_TYPE_MY_TIMER (mathg_my_timer_get_type ())
typedef struct _mathgMyTimer mathgMyTimer;

#define MATHG_TYPE_ELMNT (mathg_elmnt_get_type ())
typedef struct _mathgElmnt mathgElmnt;
typedef struct _mathgMathCog mathgMathCog;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _mathgNumberUtils {
	guint bas;
};

struct _mathgOperate {
	gint64 max;
	gint64 min;
	gint term;
	gchar* type;
};

struct _mathgMyTimer {
	gboolean reset;
	GDateTime* start;
	GDateTime* stop;
};

struct _mathgElmnt {
	gint64 answer;
	gchar* guess;
	gchar* question;
	gchar* result;
};

struct _mathgMathCog {
	gchar* ch;
	guint64 cor;
	gdouble deviation;
	guint64 err;
	gboolean isenter;
	mathgNumberUtils nu;
	mathgOperate operation;
	gint pm;
	mathgMyTimer problem;
	gchar* res;
	mathgElmnt* stra;
	gint stra_length1;
	gint straind;
	mathgMyTimer total;
};



#define MATHG_digits "0123456789abcdefghijklmnopqrstuvwxyz"
GType mathg_math_cog_get_type (void) G_GNUC_CONST;
GType mathg_number_utils_get_type (void) G_GNUC_CONST;
mathgNumberUtils* mathg_number_utils_dup (const mathgNumberUtils* self);
void mathg_number_utils_free (mathgNumberUtils* self);
GType mathg_operate_get_type (void) G_GNUC_CONST;
mathgOperate* mathg_operate_dup (const mathgOperate* self);
void mathg_operate_free (mathgOperate* self);
void mathg_operate_copy (const mathgOperate* self, mathgOperate* dest);
void mathg_operate_destroy (mathgOperate* self);
GType mathg_my_timer_get_type (void) G_GNUC_CONST;
mathgMyTimer* mathg_my_timer_dup (const mathgMyTimer* self);
void mathg_my_timer_free (mathgMyTimer* self);
void mathg_my_timer_copy (const mathgMyTimer* self, mathgMyTimer* dest);
void mathg_my_timer_destroy (mathgMyTimer* self);
GType mathg_elmnt_get_type (void) G_GNUC_CONST;
mathgElmnt* mathg_elmnt_dup (const mathgElmnt* self);
void mathg_elmnt_free (mathgElmnt* self);
void mathg_elmnt_copy (const mathgElmnt* self, mathgElmnt* dest);
void mathg_elmnt_destroy (mathgElmnt* self);
mathgMathCog* mathg_math_cog_dup (const mathgMathCog* self);
void mathg_math_cog_free (mathgMathCog* self);
void mathg_math_cog_copy (const mathgMathCog* self, mathgMathCog* dest);
void mathg_math_cog_destroy (mathgMathCog* self);
static void _vala_mathgElmnt_array_free (mathgElmnt* array, gint array_length);
void mathg_math_cog_init (mathgMathCog *self, gchar** args, int args_length1);
void mathg_number_utils_init (mathgNumberUtils *self, const gchar* s);
gint mathg_number_utils_ti (mathgNumberUtils *self, const gchar* a);
gint64 mathg_number_utils_tl (mathgNumberUtils *self, const gchar* a);
void mathg_operate_init (mathgOperate *self, gint64 a, gint64 b, const gchar* c, gint d);
gdouble mathg_number_utils_td (mathgNumberUtils *self, const gchar* a);
void mathg_math_cog_generate (mathgMathCog *self);
void mathg_math_cog_bsp (mathgMathCog *self);
static void mathg_math_cog_close (mathgMathCog *self, gint64 ans);
gchar* mathg_number_utils_ts (mathgNumberUtils *self, gint64 a);
gchar* mathg_number_utils_uts (mathgNumberUtils *self, guint64 a);
gchar* mathg_my_timer_to_string (mathgMyTimer *self);
void mathg_my_timer_init (mathgMyTimer *self, gboolean b);
void mathg_operate_oper (mathgOperate *self, mathgMathCog* mc, gint i);
void mathg_math_cog_put (mathgMathCog *self);
static mathgElmnt* _vala_array_dup1 (mathgElmnt* self, int length);


static void _vala_mathgElmnt_array_free (mathgElmnt* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			mathg_elmnt_destroy (&array[i]);
		}
	}
	g_free (array);
}


void mathg_math_cog_init (mathgMathCog *self, gchar** args, int args_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	const gchar* _tmp1_;
	gint _tmp2_ = 0;
	gchar** _tmp3_;
	gint _tmp3__length1;
	const gchar* _tmp4_;
	gint64 _tmp5_ = 0LL;
	gchar** _tmp6_;
	gint _tmp6__length1;
	const gchar* _tmp7_;
	gint64 _tmp8_ = 0LL;
	gchar** _tmp9_;
	gint _tmp9__length1;
	const gchar* _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	const gchar* _tmp12_;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gchar** _tmp15_;
	gint _tmp15__length1;
	const gchar* _tmp16_;
	gint _tmp17_ = 0;
	gint _tmp21_;
	mathgElmnt* _tmp22_ = NULL;
	gchar** _tmp23_;
	gint _tmp23__length1;
	const gchar* _tmp24_;
	gdouble _tmp25_ = 0.0;
	memset (self, 0, sizeof (mathgMathCog));
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp1_ = _tmp0_[0];
	mathg_number_utils_init (&(*self).nu, _tmp1_);
	_tmp2_ = mathg_number_utils_ti (&(*self).nu, "1000");
	(*self).pm = _tmp2_;
	_tmp3_ = args;
	_tmp3__length1 = args_length1;
	_tmp4_ = _tmp3_[1];
	_tmp5_ = mathg_number_utils_tl (&(*self).nu, _tmp4_);
	_tmp6_ = args;
	_tmp6__length1 = args_length1;
	_tmp7_ = _tmp6_[2];
	_tmp8_ = mathg_number_utils_tl (&(*self).nu, _tmp7_);
	_tmp9_ = args;
	_tmp9__length1 = args_length1;
	_tmp10_ = _tmp9_[3];
	_tmp11_ = args;
	_tmp11__length1 = args_length1;
	_tmp12_ = _tmp11_[4];
	_tmp13_ = mathg_number_utils_ti (&(*self).nu, _tmp12_);
	mathg_operate_destroy (&(*self).operation);
	mathg_operate_init (&(*self).operation, _tmp5_, _tmp8_, _tmp10_, _tmp13_);
	_tmp15_ = args;
	_tmp15__length1 = args_length1;
	_tmp16_ = _tmp15_[5];
	_tmp17_ = mathg_number_utils_ti (&(*self).nu, _tmp16_);
	if (_tmp17_ > 1) {
		gchar** _tmp18_;
		gint _tmp18__length1;
		const gchar* _tmp19_;
		gint _tmp20_ = 0;
		_tmp18_ = args;
		_tmp18__length1 = args_length1;
		_tmp19_ = _tmp18_[5];
		_tmp20_ = mathg_number_utils_ti (&(*self).nu, _tmp19_);
		_tmp14_ = _tmp20_;
	} else {
		_tmp14_ = 1;
	}
	_tmp21_ = _tmp14_;
	_tmp22_ = g_new0 (mathgElmnt, _tmp21_);
	(*self).stra = (_vala_mathgElmnt_array_free ((*self).stra, (*self).stra_length1), NULL);
	(*self).stra = _tmp22_;
	(*self).stra_length1 = _tmp21_;
	_tmp23_ = args;
	_tmp23__length1 = args_length1;
	_tmp24_ = _tmp23_[6];
	_tmp25_ = mathg_number_utils_td (&(*self).nu, _tmp24_);
	(*self).deviation = _tmp25_;
	mathg_math_cog_generate (&(*self));
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* end;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	gboolean _tmp3_;
	glong _tmp9_;
	glong _tmp15_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	_tmp3_ = _tmp0_;
	if (_tmp3_) {
		glong _tmp4_;
		glong _tmp5_;
		glong _tmp6_ = 0L;
		_tmp4_ = offset;
		_tmp5_ = len;
		_tmp6_ = string_strnlen ((gchar*) self, _tmp4_ + _tmp5_);
		string_length = _tmp6_;
	} else {
		gint _tmp7_;
		gint _tmp8_;
		_tmp7_ = strlen (self);
		_tmp8_ = _tmp7_;
		string_length = (glong) _tmp8_;
	}
	_tmp9_ = offset;
	if (_tmp9_ < ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		glong _tmp12_;
		_tmp10_ = string_length;
		_tmp11_ = offset;
		offset = _tmp10_ + _tmp11_;
		_tmp12_ = offset;
		g_return_val_if_fail (_tmp12_ >= ((glong) 0), NULL);
	} else {
		glong _tmp13_;
		glong _tmp14_;
		_tmp13_ = offset;
		_tmp14_ = string_length;
		g_return_val_if_fail (_tmp13_ <= _tmp14_, NULL);
	}
	_tmp15_ = len;
	if (_tmp15_ < ((glong) 0)) {
		glong _tmp16_;
		glong _tmp17_;
		_tmp16_ = string_length;
		_tmp17_ = offset;
		len = _tmp16_ - _tmp17_;
	}
	_tmp18_ = offset;
	_tmp19_ = len;
	_tmp20_ = string_length;
	g_return_val_if_fail ((_tmp18_ + _tmp19_) <= _tmp20_, NULL);
	_tmp21_ = offset;
	_tmp22_ = len;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp21_, (gsize) _tmp22_);
	result = _tmp23_;
	return result;
}


void mathg_math_cog_bsp (mathgMathCog *self) {
	mathgElmnt* _tmp0_;
	gint _tmp0__length1;
	gint _tmp1_;
	mathgElmnt _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* s;
	mathgElmnt* _tmp5_;
	gint _tmp5__length1;
	gint _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gchar* _tmp9_ = NULL;
	_tmp0_ = (*self).stra;
	_tmp0__length1 = (*self).stra_length1;
	_tmp1_ = (*self).straind;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _tmp2_.guess;
	_tmp4_ = g_strdup (_tmp3_);
	s = _tmp4_;
	_tmp5_ = (*self).stra;
	_tmp5__length1 = (*self).stra_length1;
	_tmp6_ = (*self).straind;
	_tmp7_ = strlen (s);
	_tmp8_ = _tmp7_;
	_tmp9_ = string_substring (s, (glong) 0, (glong) (_tmp8_ - 1));
	_g_free0 (_tmp5_[_tmp6_].guess);
	_tmp5_[_tmp6_].guess = _tmp9_;
	_g_free0 (s);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void mathg_math_cog_close (mathgMathCog *self, gint64 ans) {
	mathgElmnt* _tmp0_;
	gint _tmp0__length1;
	gint _tmp1_;
	mathgElmnt _tmp2_;
	const gchar* _tmp3_;
	gint64 _tmp4_ = 0LL;
	gint64 hyp;
	gint64 _tmp5_;
	gint64 _tmp6_;
	gint64 _tmp7_ = 0LL;
	guint64 d;
	guint64 _tmp8_;
	gint64 _tmp9_;
	gint64 _tmp10_ = 0LL;
	guint64 _tmp11_;
	guint64 _tmp12_;
	mathgElmnt* _tmp13_;
	gint _tmp13__length1;
	gint _tmp14_;
	gint64 _tmp15_;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	const gchar* _tmp18_ = NULL;
	guint64 _tmp19_;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	mathgElmnt* _tmp24_;
	gint _tmp24__length1;
	gint _tmp25_;
	mathgElmnt* _tmp26_;
	gint _tmp26__length1;
	gint _tmp27_;
	const gchar* _tmp28_;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* _tmp34_;
	const gchar* _tmp35_;
	guint64 _tmp36_;
	guint64 _tmp37_;
	gint _tmp38_;
	gchar* _tmp39_ = NULL;
	gchar* _tmp40_;
	gchar* _tmp41_;
	const gchar* _tmp42_;
	guint64 _tmp43_;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_;
	const gchar* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_;
	gchar* _tmp49_ = NULL;
	gchar* _tmp50_;
	gchar* _tmp51_;
	gint _tmp52_ = 0;
	gint _tmp53_;
	mathgElmnt* _tmp54_;
	gint _tmp54__length1;
	gint _tmp55_;
	gint _tmp56_;
	_tmp0_ = (*self).stra;
	_tmp0__length1 = (*self).stra_length1;
	_tmp1_ = (*self).straind;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _tmp2_.guess;
	_tmp4_ = mathg_number_utils_tl (&(*self).nu, _tmp3_);
	hyp = _tmp4_;
	_tmp5_ = hyp;
	_tmp6_ = ans;
	_tmp7_ = llabs (_tmp5_ - _tmp6_);
	d = (guint64) _tmp7_;
	_tmp8_ = (*self).cor;
	_tmp9_ = ans;
	_tmp10_ = llabs (_tmp9_);
	(*self).cor = _tmp8_ + _tmp10_;
	_tmp11_ = (*self).err;
	_tmp12_ = d;
	(*self).err = _tmp11_ + _tmp12_;
	_tmp13_ = (*self).stra;
	_tmp13__length1 = (*self).stra_length1;
	_tmp14_ = (*self).straind;
	_tmp15_ = ans;
	_tmp16_ = mathg_number_utils_ts (&(*self).nu, _tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = string_to_string (_tmp17_);
	_tmp19_ = d;
	_tmp20_ = mathg_number_utils_uts (&(*self).nu, _tmp19_);
	_tmp21_ = _tmp20_;
	_tmp22_ = string_to_string (_tmp21_);
	_tmp23_ = g_strconcat (" ans=", _tmp18_, " Δ=", _tmp22_, " t=", NULL);
	_g_free0 (_tmp13_[_tmp14_].result);
	_tmp13_[_tmp14_].result = _tmp23_;
	_g_free0 (_tmp21_);
	_g_free0 (_tmp17_);
	_tmp24_ = (*self).stra;
	_tmp24__length1 = (*self).stra_length1;
	_tmp25_ = (*self).straind;
	_tmp26_ = (*self).stra;
	_tmp26__length1 = (*self).stra_length1;
	_tmp27_ = (*self).straind;
	_tmp28_ = _tmp26_[_tmp27_].result;
	_tmp29_ = mathg_my_timer_to_string (&(*self).problem);
	_tmp30_ = _tmp29_;
	_tmp31_ = g_strconcat (_tmp30_, "ms", NULL);
	_tmp32_ = _tmp31_;
	_tmp33_ = g_strconcat (_tmp28_, _tmp32_, NULL);
	_g_free0 (_tmp26_[_tmp27_].result);
	_tmp26_[_tmp27_].result = _tmp33_;
	_g_free0 (_tmp32_);
	_g_free0 (_tmp30_);
	_tmp34_ = g_strdup ("tot Δ‰=");
	_g_free0 ((*self).res);
	(*self).res = _tmp34_;
	_tmp35_ = (*self).res;
	_tmp36_ = (*self).err;
	_tmp37_ = (*self).cor;
	_tmp38_ = (*self).pm;
	_tmp39_ = mathg_number_utils_uts (&(*self).nu, (guint64) ((((gdouble) _tmp36_) / _tmp37_) * _tmp38_));
	_tmp40_ = _tmp39_;
	_tmp41_ = g_strconcat (_tmp35_, _tmp40_, NULL);
	_g_free0 ((*self).res);
	(*self).res = _tmp41_;
	_g_free0 (_tmp40_);
	_tmp42_ = (*self).res;
	_tmp43_ = (*self).err;
	_tmp44_ = mathg_number_utils_uts (&(*self).nu, _tmp43_);
	_tmp45_ = _tmp44_;
	_tmp46_ = string_to_string (_tmp45_);
	_tmp47_ = mathg_my_timer_to_string (&(*self).total);
	_tmp48_ = _tmp47_;
	_tmp49_ = g_strconcat (" Δ=", _tmp46_, " t=", _tmp48_, "ms", NULL);
	_tmp50_ = _tmp49_;
	_tmp51_ = g_strconcat (_tmp42_, _tmp50_, NULL);
	_g_free0 ((*self).res);
	(*self).res = _tmp51_;
	_g_free0 (_tmp50_);
	_g_free0 (_tmp48_);
	_g_free0 (_tmp45_);
	_tmp53_ = (*self).straind;
	_tmp54_ = (*self).stra;
	_tmp54__length1 = (*self).stra_length1;
	if (_tmp53_ < (_tmp54__length1 - 1)) {
		_tmp52_ = 1;
	} else {
		_tmp52_ = 0;
	}
	_tmp55_ = (*self).straind;
	_tmp56_ = _tmp52_;
	(*self).straind = _tmp55_ + _tmp56_;
}


void mathg_math_cog_generate (mathgMathCog *self) {
	gint _tmp0_;
	guint64 _tmp1_;
	gchar* _tmp2_;
	(*self).straind = 0;
	_tmp0_ = (*self).straind;
	(*self).err = (guint64) _tmp0_;
	_tmp1_ = (*self).err;
	(*self).cor = _tmp1_;
	_tmp2_ = g_strdup ("tot Δ‰=0 Δ=0 t=0ms");
	_g_free0 ((*self).res);
	(*self).res = _tmp2_;
	mathg_my_timer_destroy (&(*self).problem);
	mathg_my_timer_init (&(*self).problem, TRUE);
	mathg_my_timer_destroy (&(*self).total);
	mathg_my_timer_init (&(*self).total, FALSE);
	{
		gint b;
		b = 0;
		{
			gboolean _tmp3_;
			_tmp3_ = TRUE;
			while (TRUE) {
				gboolean _tmp4_;
				gint _tmp6_;
				mathgElmnt* _tmp7_;
				gint _tmp7__length1;
				gint _tmp8_;
				_tmp4_ = _tmp3_;
				if (!_tmp4_) {
					gint _tmp5_;
					_tmp5_ = b;
					b = _tmp5_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp6_ = b;
				_tmp7_ = (*self).stra;
				_tmp7__length1 = (*self).stra_length1;
				if (!(_tmp6_ < _tmp7__length1)) {
					break;
				}
				_tmp8_ = b;
				mathg_operate_oper (&(*self).operation, &(*self), _tmp8_);
			}
		}
	}
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


void mathg_math_cog_put (mathgMathCog *self) {
	mathgElmnt* _tmp0_;
	gint _tmp0__length1;
	gint _tmp1_;
	mathgElmnt _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* s;
	const gchar* _tmp5_;
	const gchar* _tmp26_;
	gdouble _tmp27_ = 0.0;
	gdouble d;
	mathgElmnt* _tmp28_;
	gint _tmp28__length1;
	gint _tmp29_;
	const gchar* _tmp30_;
	gchar* _tmp31_;
	mathgElmnt* _tmp32_;
	gint _tmp32__length1;
	gint _tmp33_;
	mathgElmnt _tmp34_;
	gint64 _tmp35_;
	gint64 ans;
	gboolean _tmp36_ = FALSE;
	gboolean _tmp37_ = FALSE;
	gdouble _tmp38_;
	gint64 _tmp39_;
	gboolean _tmp44_;
	gboolean _tmp46_;
	_tmp0_ = (*self).stra;
	_tmp0__length1 = (*self).stra_length1;
	_tmp1_ = (*self).straind;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _tmp2_.guess;
	_tmp4_ = g_strdup (_tmp3_);
	s = _tmp4_;
	_tmp5_ = (*self).ch;
	if (g_strcmp0 (_tmp5_, "-") == 0) {
		gchar* _tmp6_ = NULL;
		const gchar* _tmp7_;
		gboolean _tmp8_ = FALSE;
		const gchar* _tmp14_;
		gchar* _tmp15_;
		_tmp7_ = s;
		_tmp8_ = string_contains (_tmp7_, "-");
		if (_tmp8_) {
			const gchar* _tmp9_;
			gchar* _tmp10_ = NULL;
			_tmp9_ = s;
			_tmp10_ = string_substring (_tmp9_, (glong) 1, (glong) (-1));
			_g_free0 (_tmp6_);
			_tmp6_ = _tmp10_;
		} else {
			const gchar* _tmp11_;
			const gchar* _tmp12_;
			gchar* _tmp13_;
			_tmp11_ = (*self).ch;
			_tmp12_ = s;
			_tmp13_ = g_strconcat (_tmp11_, _tmp12_, NULL);
			_g_free0 (_tmp6_);
			_tmp6_ = _tmp13_;
		}
		_tmp14_ = _tmp6_;
		_tmp15_ = g_strdup (_tmp14_);
		_g_free0 (s);
		s = _tmp15_;
		_g_free0 (_tmp6_);
	} else {
		mathgNumberUtils _tmp16_;
		guint _tmp17_;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_;
		const gchar* _tmp20_;
		gboolean _tmp21_ = FALSE;
		gboolean _tmp22_;
		_tmp16_ = (*self).nu;
		_tmp17_ = _tmp16_.bas;
		_tmp18_ = string_substring (MATHG_digits, (glong) 0, (glong) _tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = (*self).ch;
		_tmp21_ = string_contains (_tmp19_, _tmp20_);
		_tmp22_ = _tmp21_;
		_g_free0 (_tmp19_);
		if (_tmp22_) {
			const gchar* _tmp23_;
			const gchar* _tmp24_;
			gchar* _tmp25_;
			_tmp23_ = s;
			_tmp24_ = (*self).ch;
			_tmp25_ = g_strconcat (_tmp23_, _tmp24_, NULL);
			_g_free0 (s);
			s = _tmp25_;
		}
	}
	_tmp26_ = s;
	_tmp27_ = mathg_number_utils_td (&(*self).nu, _tmp26_);
	d = _tmp27_;
	_tmp28_ = (*self).stra;
	_tmp28__length1 = (*self).stra_length1;
	_tmp29_ = (*self).straind;
	_tmp30_ = s;
	_tmp31_ = g_strdup (_tmp30_);
	_g_free0 (_tmp28_[_tmp29_].guess);
	_tmp28_[_tmp29_].guess = _tmp31_;
	_tmp32_ = (*self).stra;
	_tmp32__length1 = (*self).stra_length1;
	_tmp33_ = (*self).straind;
	_tmp34_ = _tmp32_[_tmp33_];
	_tmp35_ = _tmp34_.answer;
	ans = _tmp35_;
	_tmp38_ = d;
	_tmp39_ = ans;
	if (((gint64) _tmp38_) == _tmp39_) {
		_tmp37_ = TRUE;
	} else {
		gdouble _tmp40_;
		gint64 _tmp41_;
		gdouble _tmp42_ = 0.0;
		gdouble _tmp43_;
		_tmp40_ = d;
		_tmp41_ = ans;
		_tmp42_ = fabs ((_tmp40_ / _tmp41_) - 1);
		_tmp43_ = (*self).deviation;
		_tmp37_ = _tmp42_ <= _tmp43_;
	}
	_tmp44_ = _tmp37_;
	if (_tmp44_) {
		_tmp36_ = TRUE;
	} else {
		gboolean _tmp45_;
		_tmp45_ = (*self).isenter;
		_tmp36_ = _tmp45_;
	}
	_tmp46_ = _tmp36_;
	if (_tmp46_) {
		gint64 _tmp47_;
		_tmp47_ = ans;
		mathg_math_cog_close (&(*self), _tmp47_);
	}
	(*self).isenter = FALSE;
	_g_free0 (s);
}


static mathgElmnt* _vala_array_dup1 (mathgElmnt* self, int length) {
	mathgElmnt* result;
	int i;
	result = g_new0 (mathgElmnt, length);
	for (i = 0; i < length; i++) {
		mathgElmnt _tmp0_ = {0};
		mathg_elmnt_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


void mathg_math_cog_copy (const mathgMathCog* self, mathgMathCog* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	guint64 _tmp2_;
	gdouble _tmp3_;
	guint64 _tmp4_;
	gboolean _tmp5_;
	mathgNumberUtils _tmp6_;
	mathgOperate _tmp7_;
	mathgOperate _tmp8_ = {0};
	gint _tmp9_;
	mathgMyTimer _tmp10_;
	mathgMyTimer _tmp11_ = {0};
	const gchar* _tmp12_;
	gchar* _tmp13_;
	mathgElmnt* _tmp14_;
	gint _tmp14__length1;
	mathgElmnt* _tmp15_;
	gint _tmp15__length1;
	gint _tmp16_;
	mathgMyTimer _tmp17_;
	mathgMyTimer _tmp18_ = {0};
	_tmp0_ = (*self).ch;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).ch);
	(*dest).ch = _tmp1_;
	_tmp2_ = (*self).cor;
	(*dest).cor = _tmp2_;
	_tmp3_ = (*self).deviation;
	(*dest).deviation = _tmp3_;
	_tmp4_ = (*self).err;
	(*dest).err = _tmp4_;
	_tmp5_ = (*self).isenter;
	(*dest).isenter = _tmp5_;
	_tmp6_ = (*self).nu;
	(*dest).nu = _tmp6_;
	_tmp7_ = (*self).operation;
	mathg_operate_copy (&_tmp7_, &_tmp8_);
	mathg_operate_destroy (&(*dest).operation);
	(*dest).operation = _tmp8_;
	_tmp9_ = (*self).pm;
	(*dest).pm = _tmp9_;
	_tmp10_ = (*self).problem;
	mathg_my_timer_copy (&_tmp10_, &_tmp11_);
	mathg_my_timer_destroy (&(*dest).problem);
	(*dest).problem = _tmp11_;
	_tmp12_ = (*self).res;
	_tmp13_ = g_strdup (_tmp12_);
	_g_free0 ((*dest).res);
	(*dest).res = _tmp13_;
	_tmp14_ = (*self).stra;
	_tmp14__length1 = (*self).stra_length1;
	_tmp15_ = (_tmp14_ != NULL) ? _vala_array_dup1 (_tmp14_, _tmp14__length1) : ((gpointer) _tmp14_);
	_tmp15__length1 = _tmp14__length1;
	(*dest).stra = (_vala_mathgElmnt_array_free ((*dest).stra, (*dest).stra_length1), NULL);
	(*dest).stra = _tmp15_;
	(*dest).stra_length1 = _tmp15__length1;
	_tmp16_ = (*self).straind;
	(*dest).straind = _tmp16_;
	_tmp17_ = (*self).total;
	mathg_my_timer_copy (&_tmp17_, &_tmp18_);
	mathg_my_timer_destroy (&(*dest).total);
	(*dest).total = _tmp18_;
}


void mathg_math_cog_destroy (mathgMathCog* self) {
	_g_free0 ((*self).ch);
	mathg_operate_destroy (&(*self).operation);
	mathg_my_timer_destroy (&(*self).problem);
	_g_free0 ((*self).res);
	(*self).stra = (_vala_mathgElmnt_array_free ((*self).stra, (*self).stra_length1), NULL);
	mathg_my_timer_destroy (&(*self).total);
}


mathgMathCog* mathg_math_cog_dup (const mathgMathCog* self) {
	mathgMathCog* dup;
	dup = g_new0 (mathgMathCog, 1);
	mathg_math_cog_copy (self, dup);
	return dup;
}


void mathg_math_cog_free (mathgMathCog* self) {
	mathg_math_cog_destroy (self);
	g_free (self);
}


GType mathg_math_cog_get_type (void) {
	static volatile gsize mathg_math_cog_type_id__volatile = 0;
	if (g_once_init_enter (&mathg_math_cog_type_id__volatile)) {
		GType mathg_math_cog_type_id;
		mathg_math_cog_type_id = g_boxed_type_register_static ("mathgMathCog", (GBoxedCopyFunc) mathg_math_cog_dup, (GBoxedFreeFunc) mathg_math_cog_free);
		g_once_init_leave (&mathg_math_cog_type_id__volatile, mathg_math_cog_type_id);
	}
	return mathg_math_cog_type_id__volatile;
}



