/* MathCog.c generated by valac 0.34.4, the Vala compiler
 * generated from MathCog.vala, do not modify */

/*Copyright (C) 2013 Mattias Münster

Author: Mattias Münster <mattiasmun@gmail.com>

This file is part of valamathg.

valamathg is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

valamathg is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with valamathg.  If not, see <http://www.gnu.org/licenses/>.*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define MATHG_TYPE_MATH_COG (mathg_math_cog_get_type ())

#define MATHG_TYPE_NUMBER_UTILS (mathg_number_utils_get_type ())
typedef struct _mathgNumberUtils mathgNumberUtils;

#define MATHG_TYPE_OPERATE (mathg_operate_get_type ())
typedef struct _mathgOperate mathgOperate;

#define MATHG_TYPE_MY_TIMER (mathg_my_timer_get_type ())
typedef struct _mathgMyTimer mathgMyTimer;

#define MATHG_TYPE_ELMNT (mathg_elmnt_get_type ())
typedef struct _mathgElmnt mathgElmnt;
typedef struct _mathgMathCog mathgMathCog;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _mathgNumberUtils {
	guint bas;
};

struct _mathgOperate {
	gdouble min;
	gdouble span;
	gint term;
	gchar* type;
};

struct _mathgMyTimer {
	gboolean reset;
	GDateTime* start;
	GDateTime* stop;
};

struct _mathgElmnt {
	gdouble answer;
	gchar* guess;
	gchar* question;
	gchar* result;
};

struct _mathgMathCog {
	gchar* ch;
	gdouble cor;
	gdouble deviation;
	gdouble err;
	gboolean isenter;
	mathgNumberUtils nu;
	mathgOperate operation;
	gint pm;
	mathgMyTimer problem;
	gchar* res;
	mathgElmnt* stra;
	gint stra_length1;
	gint straind;
	mathgMyTimer total;
};



#define MATHG_digits "0123456789abcdefghijklmnopqrstuvwxyz"
GType mathg_math_cog_get_type (void) G_GNUC_CONST;
GType mathg_number_utils_get_type (void) G_GNUC_CONST;
mathgNumberUtils* mathg_number_utils_dup (const mathgNumberUtils* self);
void mathg_number_utils_free (mathgNumberUtils* self);
GType mathg_operate_get_type (void) G_GNUC_CONST;
mathgOperate* mathg_operate_dup (const mathgOperate* self);
void mathg_operate_free (mathgOperate* self);
void mathg_operate_copy (const mathgOperate* self, mathgOperate* dest);
void mathg_operate_destroy (mathgOperate* self);
GType mathg_my_timer_get_type (void) G_GNUC_CONST;
mathgMyTimer* mathg_my_timer_dup (const mathgMyTimer* self);
void mathg_my_timer_free (mathgMyTimer* self);
void mathg_my_timer_copy (const mathgMyTimer* self, mathgMyTimer* dest);
void mathg_my_timer_destroy (mathgMyTimer* self);
GType mathg_elmnt_get_type (void) G_GNUC_CONST;
mathgElmnt* mathg_elmnt_dup (const mathgElmnt* self);
void mathg_elmnt_free (mathgElmnt* self);
void mathg_elmnt_copy (const mathgElmnt* self, mathgElmnt* dest);
void mathg_elmnt_destroy (mathgElmnt* self);
mathgMathCog* mathg_math_cog_dup (const mathgMathCog* self);
void mathg_math_cog_free (mathgMathCog* self);
void mathg_math_cog_copy (const mathgMathCog* self, mathgMathCog* dest);
void mathg_math_cog_destroy (mathgMathCog* self);
static void _vala_mathgElmnt_array_free (mathgElmnt* array, gint array_length);
void mathg_math_cog_init (mathgMathCog *self, gchar** args, int args_length1);
void mathg_number_utils_init (mathgNumberUtils *self, const gchar* s);
gint mathg_number_utils_ti (mathgNumberUtils *self, const gchar* a);
gdouble mathg_number_utils_td (mathgNumberUtils *self, const gchar* a);
void mathg_operate_init (mathgOperate *self, gdouble a, gdouble b, const gchar* c, gint d);
void mathg_math_cog_generate (mathgMathCog *self);
void mathg_math_cog_bsp (mathgMathCog *self);
static void mathg_math_cog_close (mathgMathCog *self, gdouble ans);
gchar* mathg_my_timer_to_string (mathgMyTimer *self);
void mathg_my_timer_init (mathgMyTimer *self, gboolean b);
void mathg_operate_oper (mathgOperate *self, mathgMathCog* mc, gint i);
void mathg_math_cog_put (mathgMathCog *self);
static mathgElmnt* _vala_array_dup1 (mathgElmnt* self, int length);


static void _vala_mathgElmnt_array_free (mathgElmnt* array, gint array_length) {
	if (array != NULL) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			mathg_elmnt_destroy (&array[i]);
		}
	}
	g_free (array);
}


void mathg_math_cog_init (mathgMathCog *self, gchar** args, int args_length1) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gchar** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	const gchar* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	gchar** _tmp6_ = NULL;
	gint _tmp6__length1 = 0;
	const gchar* _tmp7_ = NULL;
	gdouble _tmp8_ = 0.0;
	gchar** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	const gchar* _tmp10_ = NULL;
	gchar** _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	const gchar* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gchar** _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	const gchar* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	mathgElmnt* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	const gchar* _tmp23_ = NULL;
	gdouble _tmp24_ = 0.0;
	memset (self, 0, sizeof (mathgMathCog));
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp1_ = _tmp0_[0];
	mathg_number_utils_init (&(*self).nu, _tmp1_);
	_tmp2_ = mathg_number_utils_ti (&(*self).nu, "1000");
	(*self).pm = _tmp2_;
	_tmp3_ = args;
	_tmp3__length1 = args_length1;
	_tmp4_ = _tmp3_[1];
	_tmp5_ = mathg_number_utils_td (&(*self).nu, _tmp4_);
	_tmp6_ = args;
	_tmp6__length1 = args_length1;
	_tmp7_ = _tmp6_[2];
	_tmp8_ = mathg_number_utils_td (&(*self).nu, _tmp7_);
	_tmp9_ = args;
	_tmp9__length1 = args_length1;
	_tmp10_ = _tmp9_[3];
	_tmp11_ = args;
	_tmp11__length1 = args_length1;
	_tmp12_ = _tmp11_[4];
	_tmp13_ = mathg_number_utils_ti (&(*self).nu, _tmp12_);
	mathg_operate_destroy (&(*self).operation);
	mathg_operate_init (&(*self).operation, _tmp5_, _tmp8_, _tmp10_, _tmp13_);
	_tmp15_ = args;
	_tmp15__length1 = args_length1;
	_tmp16_ = _tmp15_[5];
	_tmp17_ = mathg_number_utils_ti (&(*self).nu, _tmp16_);
	if (_tmp17_ > 1) {
		gchar** _tmp18_ = NULL;
		gint _tmp18__length1 = 0;
		const gchar* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		_tmp18_ = args;
		_tmp18__length1 = args_length1;
		_tmp19_ = _tmp18_[5];
		_tmp20_ = mathg_number_utils_ti (&(*self).nu, _tmp19_);
		_tmp14_ = _tmp20_;
	} else {
		_tmp14_ = 1;
	}
	_tmp21_ = g_new0 (mathgElmnt, _tmp14_);
	(*self).stra = (_vala_mathgElmnt_array_free ((*self).stra, (*self).stra_length1), NULL);
	(*self).stra = _tmp21_;
	(*self).stra_length1 = _tmp14_;
	_tmp22_ = args;
	_tmp22__length1 = args_length1;
	_tmp23_ = _tmp22_[6];
	_tmp24_ = mathg_number_utils_td (&(*self).nu, _tmp23_);
	(*self).deviation = _tmp24_;
	mathg_math_cog_generate (&(*self));
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


void mathg_math_cog_bsp (mathgMathCog *self) {
	gchar* s = NULL;
	mathgElmnt* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	mathgElmnt _tmp2_ = {0};
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	mathgElmnt* _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gchar* _tmp9_ = NULL;
	_tmp0_ = (*self).stra;
	_tmp0__length1 = (*self).stra_length1;
	_tmp1_ = (*self).straind;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _tmp2_.guess;
	_tmp4_ = g_strdup (_tmp3_);
	s = _tmp4_;
	_tmp5_ = (*self).stra;
	_tmp5__length1 = (*self).stra_length1;
	_tmp6_ = (*self).straind;
	_tmp7_ = strlen (s);
	_tmp8_ = _tmp7_;
	_tmp9_ = string_substring (s, (glong) 0, (glong) (_tmp8_ - 1));
	_g_free0 (_tmp5_[_tmp6_].guess);
	_tmp5_[_tmp6_].guess = _tmp9_;
	_g_free0 (s);
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


static void mathg_math_cog_close (mathgMathCog *self, gdouble ans) {
	gdouble hyp = 0.0;
	mathgElmnt* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	mathgElmnt _tmp2_ = {0};
	const gchar* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	gdouble d = 0.0;
	gdouble _tmp5_ = 0.0;
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	gdouble _tmp9_ = 0.0;
	gdouble _tmp10_ = 0.0;
	gdouble _tmp11_ = 0.0;
	gdouble _tmp12_ = 0.0;
	mathgElmnt* _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	gint _tmp14_ = 0;
	gdouble _tmp15_ = 0.0;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gdouble _tmp18_ = 0.0;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	mathgElmnt* _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	gint _tmp23_ = 0;
	mathgElmnt* _tmp24_ = NULL;
	gint _tmp24__length1 = 0;
	gint _tmp25_ = 0;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	const gchar* _tmp33_ = NULL;
	gdouble _tmp34_ = 0.0;
	gdouble _tmp35_ = 0.0;
	gint _tmp36_ = 0;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	const gchar* _tmp40_ = NULL;
	gdouble _tmp41_ = 0.0;
	gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gchar* _tmp45_ = NULL;
	gchar* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	gint _tmp49_ = 0;
	gint _tmp50_ = 0;
	mathgElmnt* _tmp51_ = NULL;
	gint _tmp51__length1 = 0;
	gint _tmp52_ = 0;
	_tmp0_ = (*self).stra;
	_tmp0__length1 = (*self).stra_length1;
	_tmp1_ = (*self).straind;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _tmp2_.guess;
	_tmp4_ = mathg_number_utils_td (&(*self).nu, _tmp3_);
	hyp = _tmp4_;
	_tmp5_ = hyp;
	_tmp6_ = ans;
	_tmp7_ = fabs (_tmp5_ - _tmp6_);
	d = _tmp7_;
	_tmp8_ = (*self).cor;
	_tmp9_ = ans;
	_tmp10_ = fabs (_tmp9_);
	(*self).cor = _tmp8_ + _tmp10_;
	_tmp11_ = (*self).err;
	_tmp12_ = d;
	(*self).err = _tmp11_ + _tmp12_;
	_tmp13_ = (*self).stra;
	_tmp13__length1 = (*self).stra_length1;
	_tmp14_ = (*self).straind;
	_tmp15_ = ans;
	_tmp16_ = double_to_string (_tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = d;
	_tmp19_ = double_to_string (_tmp18_);
	_tmp20_ = _tmp19_;
	_tmp21_ = g_strconcat (" ans=", _tmp17_, " Δ=", _tmp20_, " t=", NULL);
	_g_free0 (_tmp13_[_tmp14_].result);
	_tmp13_[_tmp14_].result = _tmp21_;
	_g_free0 (_tmp20_);
	_g_free0 (_tmp17_);
	_tmp22_ = (*self).stra;
	_tmp22__length1 = (*self).stra_length1;
	_tmp23_ = (*self).straind;
	_tmp24_ = (*self).stra;
	_tmp24__length1 = (*self).stra_length1;
	_tmp25_ = (*self).straind;
	_tmp26_ = _tmp24_[_tmp25_].result;
	_tmp27_ = mathg_my_timer_to_string (&(*self).problem);
	_tmp28_ = _tmp27_;
	_tmp29_ = g_strconcat (_tmp28_, "ms", NULL);
	_tmp30_ = _tmp29_;
	_tmp31_ = g_strconcat (_tmp26_, _tmp30_, NULL);
	_g_free0 (_tmp24_[_tmp25_].result);
	_tmp24_[_tmp25_].result = _tmp31_;
	_g_free0 (_tmp30_);
	_g_free0 (_tmp28_);
	_tmp32_ = g_strdup ("tot Δ‰=");
	_g_free0 ((*self).res);
	(*self).res = _tmp32_;
	_tmp33_ = (*self).res;
	_tmp34_ = (*self).err;
	_tmp35_ = (*self).cor;
	_tmp36_ = (*self).pm;
	_tmp37_ = double_to_string ((_tmp34_ / _tmp35_) * _tmp36_);
	_tmp38_ = _tmp37_;
	_tmp39_ = g_strconcat (_tmp33_, _tmp38_, NULL);
	_g_free0 ((*self).res);
	(*self).res = _tmp39_;
	_g_free0 (_tmp38_);
	_tmp40_ = (*self).res;
	_tmp41_ = (*self).err;
	_tmp42_ = double_to_string (_tmp41_);
	_tmp43_ = _tmp42_;
	_tmp44_ = mathg_my_timer_to_string (&(*self).total);
	_tmp45_ = _tmp44_;
	_tmp46_ = g_strconcat (" Δ=", _tmp43_, " t=", _tmp45_, "ms", NULL);
	_tmp47_ = _tmp46_;
	_tmp48_ = g_strconcat (_tmp40_, _tmp47_, NULL);
	_g_free0 ((*self).res);
	(*self).res = _tmp48_;
	_g_free0 (_tmp47_);
	_g_free0 (_tmp45_);
	_g_free0 (_tmp43_);
	_tmp50_ = (*self).straind;
	_tmp51_ = (*self).stra;
	_tmp51__length1 = (*self).stra_length1;
	if (_tmp50_ < (_tmp51__length1 - 1)) {
		_tmp49_ = 1;
	} else {
		_tmp49_ = 0;
	}
	_tmp52_ = (*self).straind;
	(*self).straind = _tmp52_ + _tmp49_;
}


void mathg_math_cog_generate (mathgMathCog *self) {
	gint _tmp0_ = 0;
	gdouble _tmp1_ = 0.0;
	gchar* _tmp2_ = NULL;
	(*self).straind = 0;
	_tmp0_ = (*self).straind;
	(*self).err = (gdouble) _tmp0_;
	_tmp1_ = (*self).err;
	(*self).cor = _tmp1_;
	_tmp2_ = g_strdup ("tot Δ‰=0 Δ=0 t=0ms");
	_g_free0 ((*self).res);
	(*self).res = _tmp2_;
	mathg_my_timer_destroy (&(*self).problem);
	mathg_my_timer_init (&(*self).problem, TRUE);
	mathg_my_timer_destroy (&(*self).total);
	mathg_my_timer_init (&(*self).total, FALSE);
	{
		gint b = 0;
		b = 0;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				gint _tmp5_ = 0;
				mathgElmnt* _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gint _tmp7_ = 0;
				if (!_tmp3_) {
					gint _tmp4_ = 0;
					_tmp4_ = b;
					b = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = b;
				_tmp6_ = (*self).stra;
				_tmp6__length1 = (*self).stra_length1;
				if (!(_tmp5_ < _tmp6__length1)) {
					break;
				}
				_tmp7_ = b;
				mathg_operate_oper (&(*self).operation, &(*self), _tmp7_);
			}
		}
	}
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


void mathg_math_cog_put (mathgMathCog *self) {
	gchar* s = NULL;
	mathgElmnt* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	mathgElmnt _tmp2_ = {0};
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	gdouble d = 0.0;
	const gchar* _tmp25_ = NULL;
	gdouble _tmp26_ = 0.0;
	mathgElmnt* _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	gint _tmp28_ = 0;
	const gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	gdouble ans = 0.0;
	mathgElmnt* _tmp31_ = NULL;
	gint _tmp31__length1 = 0;
	gint _tmp32_ = 0;
	mathgElmnt _tmp33_ = {0};
	gdouble _tmp34_ = 0.0;
	gboolean _tmp35_ = FALSE;
	gdouble _tmp36_ = 0.0;
	gdouble _tmp37_ = 0.0;
	gdouble _tmp38_ = 0.0;
	gdouble _tmp39_ = 0.0;
	_tmp0_ = (*self).stra;
	_tmp0__length1 = (*self).stra_length1;
	_tmp1_ = (*self).straind;
	_tmp2_ = _tmp0_[_tmp1_];
	_tmp3_ = _tmp2_.guess;
	_tmp4_ = g_strdup (_tmp3_);
	s = _tmp4_;
	_tmp5_ = (*self).ch;
	if (g_strcmp0 (_tmp5_, "-") == 0) {
		gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gboolean _tmp8_ = FALSE;
		gchar* _tmp14_ = NULL;
		_tmp7_ = s;
		_tmp8_ = string_contains (_tmp7_, "-");
		if (_tmp8_) {
			const gchar* _tmp9_ = NULL;
			gchar* _tmp10_ = NULL;
			_tmp9_ = s;
			_tmp10_ = string_substring (_tmp9_, (glong) 1, (glong) -1);
			_g_free0 (_tmp6_);
			_tmp6_ = _tmp10_;
		} else {
			const gchar* _tmp11_ = NULL;
			const gchar* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			_tmp11_ = (*self).ch;
			_tmp12_ = s;
			_tmp13_ = g_strconcat (_tmp11_, _tmp12_, NULL);
			_g_free0 (_tmp6_);
			_tmp6_ = _tmp13_;
		}
		_tmp14_ = g_strdup (_tmp6_);
		_g_free0 (s);
		s = _tmp14_;
		_g_free0 (_tmp6_);
	} else {
		mathgNumberUtils _tmp15_ = {0};
		guint _tmp16_ = 0U;
		gchar* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		const gchar* _tmp19_ = NULL;
		gboolean _tmp20_ = FALSE;
		gboolean _tmp21_ = FALSE;
		_tmp15_ = (*self).nu;
		_tmp16_ = _tmp15_.bas;
		_tmp17_ = string_substring (MATHG_digits, (glong) 0, (glong) _tmp16_);
		_tmp18_ = _tmp17_;
		_tmp19_ = (*self).ch;
		_tmp20_ = string_contains (_tmp18_, _tmp19_);
		_tmp21_ = _tmp20_;
		_g_free0 (_tmp18_);
		if (_tmp21_) {
			const gchar* _tmp22_ = NULL;
			const gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			_tmp22_ = s;
			_tmp23_ = (*self).ch;
			_tmp24_ = g_strconcat (_tmp22_, _tmp23_, NULL);
			_g_free0 (s);
			s = _tmp24_;
		}
	}
	_tmp25_ = s;
	_tmp26_ = mathg_number_utils_td (&(*self).nu, _tmp25_);
	d = _tmp26_;
	_tmp27_ = (*self).stra;
	_tmp27__length1 = (*self).stra_length1;
	_tmp28_ = (*self).straind;
	_tmp29_ = s;
	_tmp30_ = g_strdup (_tmp29_);
	_g_free0 (_tmp27_[_tmp28_].guess);
	_tmp27_[_tmp28_].guess = _tmp30_;
	_tmp31_ = (*self).stra;
	_tmp31__length1 = (*self).stra_length1;
	_tmp32_ = (*self).straind;
	_tmp33_ = _tmp31_[_tmp32_];
	_tmp34_ = _tmp33_.answer;
	ans = _tmp34_;
	_tmp36_ = d;
	_tmp37_ = ans;
	_tmp38_ = fabs ((_tmp36_ / _tmp37_) - 1);
	_tmp39_ = (*self).deviation;
	if (_tmp38_ <= _tmp39_) {
		_tmp35_ = TRUE;
	} else {
		gboolean _tmp40_ = FALSE;
		_tmp40_ = (*self).isenter;
		_tmp35_ = _tmp40_;
	}
	if (_tmp35_) {
		gdouble _tmp41_ = 0.0;
		_tmp41_ = ans;
		mathg_math_cog_close (&(*self), _tmp41_);
	}
	(*self).isenter = FALSE;
	_g_free0 (s);
}


static mathgElmnt* _vala_array_dup1 (mathgElmnt* self, int length) {
	mathgElmnt* result;
	int i;
	result = g_new0 (mathgElmnt, length);
	for (i = 0; i < length; i++) {
		mathgElmnt _tmp0_ = {0};
		mathg_elmnt_copy (&self[i], &_tmp0_);
		result[i] = _tmp0_;
	}
	return result;
}


void mathg_math_cog_copy (const mathgMathCog* self, mathgMathCog* dest) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gboolean _tmp5_ = FALSE;
	mathgNumberUtils _tmp6_ = {0};
	mathgOperate _tmp7_ = {0};
	mathgOperate _tmp8_ = {0};
	gint _tmp9_ = 0;
	mathgMyTimer _tmp10_ = {0};
	mathgMyTimer _tmp11_ = {0};
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	mathgElmnt* _tmp14_ = NULL;
	gint _tmp14__length1 = 0;
	mathgElmnt* _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	gint _tmp16_ = 0;
	mathgMyTimer _tmp17_ = {0};
	mathgMyTimer _tmp18_ = {0};
	_tmp0_ = (*self).ch;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).ch);
	(*dest).ch = _tmp1_;
	_tmp2_ = (*self).cor;
	(*dest).cor = _tmp2_;
	_tmp3_ = (*self).deviation;
	(*dest).deviation = _tmp3_;
	_tmp4_ = (*self).err;
	(*dest).err = _tmp4_;
	_tmp5_ = (*self).isenter;
	(*dest).isenter = _tmp5_;
	_tmp6_ = (*self).nu;
	(*dest).nu = _tmp6_;
	_tmp7_ = (*self).operation;
	mathg_operate_copy (&_tmp7_, &_tmp8_);
	mathg_operate_destroy (&(*dest).operation);
	(*dest).operation = _tmp8_;
	_tmp9_ = (*self).pm;
	(*dest).pm = _tmp9_;
	_tmp10_ = (*self).problem;
	mathg_my_timer_copy (&_tmp10_, &_tmp11_);
	mathg_my_timer_destroy (&(*dest).problem);
	(*dest).problem = _tmp11_;
	_tmp12_ = (*self).res;
	_tmp13_ = g_strdup (_tmp12_);
	_g_free0 ((*dest).res);
	(*dest).res = _tmp13_;
	_tmp14_ = (*self).stra;
	_tmp14__length1 = (*self).stra_length1;
	_tmp15_ = (_tmp14_ != NULL) ? _vala_array_dup1 (_tmp14_, _tmp14__length1) : ((gpointer) _tmp14_);
	_tmp15__length1 = _tmp14__length1;
	(*dest).stra = (_vala_mathgElmnt_array_free ((*dest).stra, (*dest).stra_length1), NULL);
	(*dest).stra = _tmp15_;
	(*dest).stra_length1 = _tmp15__length1;
	_tmp16_ = (*self).straind;
	(*dest).straind = _tmp16_;
	_tmp17_ = (*self).total;
	mathg_my_timer_copy (&_tmp17_, &_tmp18_);
	mathg_my_timer_destroy (&(*dest).total);
	(*dest).total = _tmp18_;
}


void mathg_math_cog_destroy (mathgMathCog* self) {
	_g_free0 ((*self).ch);
	mathg_operate_destroy (&(*self).operation);
	mathg_my_timer_destroy (&(*self).problem);
	_g_free0 ((*self).res);
	(*self).stra = (_vala_mathgElmnt_array_free ((*self).stra, (*self).stra_length1), NULL);
	mathg_my_timer_destroy (&(*self).total);
}


mathgMathCog* mathg_math_cog_dup (const mathgMathCog* self) {
	mathgMathCog* dup;
	dup = g_new0 (mathgMathCog, 1);
	mathg_math_cog_copy (self, dup);
	return dup;
}


void mathg_math_cog_free (mathgMathCog* self) {
	mathg_math_cog_destroy (self);
	g_free (self);
}


GType mathg_math_cog_get_type (void) {
	static volatile gsize mathg_math_cog_type_id__volatile = 0;
	if (g_once_init_enter (&mathg_math_cog_type_id__volatile)) {
		GType mathg_math_cog_type_id;
		mathg_math_cog_type_id = g_boxed_type_register_static ("mathgMathCog", (GBoxedCopyFunc) mathg_math_cog_dup, (GBoxedFreeFunc) mathg_math_cog_free);
		g_once_init_leave (&mathg_math_cog_type_id__volatile, mathg_math_cog_type_id);
	}
	return mathg_math_cog_type_id__volatile;
}



